# Generated by ariadne-codegen
# Source: graphql_to_mcp/queries.graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import Product


class ProductById(BaseModel):
    product: Optional["ProductByIdProduct"]


class ProductByIdProduct(Product):
    pass


ProductById.model_rebuild()
