# Generated by ariadne-codegen
# Source: graphql_to_mcp/queries.graphql

from typing import List, Optional

from .base_model import BaseModel
from .fragments import Product


class ProductSearch(BaseModel):
    products: Optional["ProductSearchProducts"]


class ProductSearchProducts(BaseModel):
    edges: List["ProductSearchProductsEdges"]


class ProductSearchProductsEdges(BaseModel):
    node: "ProductSearchProductsEdgesNode"


class ProductSearchProductsEdgesNode(Product):
    pass


ProductSearch.model_rebuild()
ProductSearchProducts.model_rebuild()
ProductSearchProductsEdges.model_rebuild()
